### ISSUE TITLE
[WIP] Keep a generic log of anonymized data

### ISSUE THREAD

**Issue by toommz** [WTTJ/ecto_anon#6]
## TODO

- [ ] Provide basic migrations [see Oban](https://github.com/sorentwo/oban/blob/main/guides/installation.md)
- [ ] Make logging optional
- [ ] Provide (hooks | behaviour) to decorate the log changeset with specific needs (anonymizing done in an async queue? add a `status`, `requested_at` and `finished_at` fields to the table structure and fill them with your own data)
  - [ ] may we return the log id in order to find it later from the async queue processing?
  - [ ] the `{source_id, source_type}` identifier tuple may serve as well to find it later

## Table structure 

| id | source_id | source_type | serialized_changeset     | inserted_at         |
|----|-----------|-------------|--------------------------|---------------------|
| 1  | 2345      | User        | '{email,<<"redacted">>}' | 2021-12-12-00:00:00 |

`serialized_changeset` can be created with:

```elixir
:io_lib.format("~p", [email: "redacted"]) |> :lists.flatten()
```
